#!/bin/sh
python longformer_finetune_dname_nepoch_nbatch_dotest_ntest_conti_saved_logd_gpu_debug.py completeness_gpt completeness_long 1 24 1 1 0 completeness_gpt completeness_gpt cuda:0 0
#python bert_longformer_finetune_dname_nepoch_nbatch_dotest_ntest_conti_saved_logd_gpu_debug.py completeness_bert completeness_bert 1 24 1 1 0 bert-completeness bert-completeness cuda:0 0

python longformer_finetune_dname_nepoch_nbatch_dotest_ntest_conti_saved_logd_gpu_debug.py nextsentenceprediction_gpt nextsentenceprediction_gpt 1 24 1 1 0 nextsentenceprediction_gpt nextsentenceprediction_gpt cuda:0 0
# python bert_longformer_finetune_dname_nepoch_nbatch_dotest_ntest_conti_saved_logd_gpu_debug.py nextsentenceprediction_bert nextsentenceprediction_bert 1 24 1 1 0 bert-nextsentenceprediction bert-nextsentenceprediction cuda:0 0
#sh test_completeness.sh
sh test_nextsentenceprediction.sh
