#!/bin/sh

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_1  coherence-whole bart_rake_1_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_2  coherence-whole bart_rake_2_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_5  coherence-whole bart_rake_5_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_10 coherence-whole bart_rake_10_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_19 coherence-whole bart_rake_19_coherence-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_1  coherence-whole bart_nomem_rake_1_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_2  coherence-whole bart_nomem_rake_2_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_5  coherence-whole bart_nomem_rake_5_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_10 coherence-whole bart_nomem_rake_10_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_19 coherence-whole bart_nomem_rake_19_coherence-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_1  coherence-whole bart_nocumul_rake_1_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_2  coherence-whole bart_nocumul_rake_2_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_5  coherence-whole bart_nocumul_rake_5_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_10 coherence-whole bart_nocumul_rake_10_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_19 coherence-whole bart_nocumul_rake_19_coherence-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_1  coherence-whole bart_nomemnocumul_rake_1_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_2  coherence-whole bart_nomemnocumul_rake_2_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_5  coherence-whole bart_nomemnocumul_rake_5_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_10 coherence-whole bart_nomemnocumul_rake_10_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_19 coherence-whole bart_nomemnocumul_rake_19_coherence-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_1  coherence-whole plotmachine_rake_1_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_2  coherence-whole plotmachine_rake_2_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_5  coherence-whole plotmachine_rake_5_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_10 coherence-whole plotmachine_rake_10_coherence-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_19 coherence-whole plotmachine_rake_19_coherence-whole cuda:0 0

