#!/bin/sh
#conda activate torch
#ml cuda
# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_1 gpt-nextsentenceprediction bart_rake_1_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_2 gpt-nextsentenceprediction bart_rake_2_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s
# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_1 gpt-nextsentenceprediction bart_nomem_rake_1_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_2 gpt-nextsentenceprediction bart_nomem_rake_2_gpt-nextsentenceprediction cuda:0 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_nomem_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_nomem_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_nomem_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_nomem_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_nomem_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s

# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_1 gpt-nextsentenceprediction bart_nocumul_rake_1_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_2 gpt-nextsentenceprediction bart_nocumul_rake_2_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_nocumul_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_nocumul_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_nocumul_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_nocumul_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_nocumul_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s

# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_1 gpt-nextsentenceprediction bart_nomemnocumul_rake_1_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
# python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_2 gpt-nextsentenceprediction bart_nomemnocumul_rake_2_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_nomemnocumul_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_nomemnocumul_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_nomemnocumul_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_nomemnocumul_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_nomemnocumul_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s
#python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_1 gpt-nextsentenceprediction plotmachine_rake_1_gpt-nextsentenceprediction cuda:0 0
#python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_2 gpt-nextsentenceprediction plotmachine_rake_2_gpt-nextsentenceprediction cuda:0 0
# sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_5 gpt-nextsentenceprediction plotmachine_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_10 gpt-nextsentenceprediction plotmachine_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_19 gpt-nextsentenceprediction plotmachine_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_30 gpt-nextsentenceprediction plotmachine_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_50 gpt-nextsentenceprediction plotmachine_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py GPTGenerations/gpt_nomemnocumul_alpha/test/generations_outputs_5  gpt-nextsentenceprediction gpt_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py GPTGenerations/gpt_nomemnocumul_alpha/test/generations_outputs_10 gpt-nextsentenceprediction gpt_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py GPTGenerations/gpt_nomemnocumul_alpha/test/generations_outputs_19 gpt-nextsentenceprediction gpt_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py GPTGenerations/gpt_nomemnocumul_alpha/test/generations_outputs_30 gpt-nextsentenceprediction gpt_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py GPTGenerations/gpt_nomemnocumul_alpha/test/generations_outputs_50 gpt-nextsentenceprediction gpt_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_wp_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_wp_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_wp_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_wp_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_wp_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_wp_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_wp_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_wp_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_wp_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_wp_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nofme/test/generations_outputs_5 gpt-nextsentenceprediction bart_nofme_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nofme/test/generations_outputs_10 gpt-nextsentenceprediction bart_nofme_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nofme/test/generations_outputs_19 gpt-nextsentenceprediction bart_nofme_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nofme/test/generations_outputs_30 gpt-nextsentenceprediction bart_nofme_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nofme/test/generations_outputs_50 gpt-nextsentenceprediction bart_nofme_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_bk_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_bk_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_bk_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_bk_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_bk_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_bk_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_bk_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_bk_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_bk_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_bk_rake_50_gpt-nextsentenceprediction cuda:0 50 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rd_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_rd_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rd_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_rd_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rd_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_rd_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rd_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_rd_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rd_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_rd_rake_50_gpt-nextsentenceprediction cuda:0 50 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_gamma_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_gamma_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_gamma_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_gamma_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_gamma_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_gamma_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_gamma_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_gamma_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_gamma_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_gamma_rake_50_gpt-nextsentenceprediction cuda:0 50 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_add_rake/test/generations_outputs_5 gpt-nextsentenceprediction bart_add_rake_5_gpt-nextsentenceprediction cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_add_rake/test/generations_outputs_10 gpt-nextsentenceprediction bart_add_rake_10_gpt-nextsentenceprediction cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_add_rake/test/generations_outputs_19 gpt-nextsentenceprediction bart_add_rake_19_gpt-nextsentenceprediction cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_add_rake/test/generations_outputs_30 gpt-nextsentenceprediction bart_add_rake_30_gpt-nextsentenceprediction cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_add_rake/test/generations_outputs_50 gpt-nextsentenceprediction bart_add_rake_50_gpt-nextsentenceprediction cuda:0 50 0
