python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_1 completeness-whole bart_rake_1_completeness-whole cuda:0 0
#!/bin/sh

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_2 completeness-whole bart_rake_2_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_3 completeness-whole bart_rake_5_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_3 completeness-whole bart_rake_10_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_3 completeness-whole bart_rake_19_completeness-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_1 completeness-whole bart_nomem_rake_1_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_2 completeness-whole bart_nomem_rake_2_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_3 completeness-whole bart_nomem_rake_5_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_3 completeness-whole bart_nomem_rake_10_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_3 completeness-whole bart_nomem_rake_19_completeness-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_1 completeness-whole bart_nocumul_rake_1_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_2 completeness-whole bart_nocumul_rake_2_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_3 completeness-whole bart_nocumul_rake_5_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_3 completeness-whole bart_nocumul_rake_10_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_3 completeness-whole bart_nocumul_rake_19_completeness-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_1 completeness-whole bart_nomemnocumul_rake_1_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_2 completeness-whole bart_nomemnocumul_rake_2_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_3 completeness-whole bart_nomemnocumul_rake_5_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_3 completeness-whole bart_nomemnocumul_rake_10_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_3 completeness-whole bart_nomemnocumul_rake_19_completeness-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_1 completeness-whole plotmachine_rake_1_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_2 completeness-whole plotmachine_rake_2_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_3 completeness-whole plotmachine_rake_5_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_3 completeness-whole plotmachine_rake_10_completeness-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_3 completeness-whole plotmachine_rake_19_completeness-whole cuda:0 0

