python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_1 logical-whole bart_rake_1_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_2 logical-whole bart_rake_2_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_3 logical-whole bart_rake_5_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_3 logical-whole bart_rake_10_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_rake/test/generations_outputs_3 logical-whole bart_rake_19_logical-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_1 logical-whole bart_nomem_rake_1_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_2 logical-whole bart_nomem_rake_2_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_3 logical-whole bart_nomem_rake_5_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_3 logical-whole bart_nomem_rake_10_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomem_rake/test/generations_outputs_3 logical-whole bart_nomem_rake_19_logical-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_1 logical-whole bart_nocumul_rake_1_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_2 logical-whole bart_nocumul_rake_2_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_3 logical-whole bart_nocumul_rake_5_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_3 logical-whole bart_nocumul_rake_10_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nocumul_rake/test/generations_outputs_3 logical-whole bart_nocumul_rake_19_logical-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_1 logical-whole bart_nomemnocumul_rake_1_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_2 logical-whole bart_nomemnocumul_rake_2_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_3 logical-whole bart_nomemnocumul_rake_5_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_3 logical-whole bart_nomemnocumul_rake_10_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/bart_nomemnocumul_rake/test/generations_outputs_3 logical-whole bart_nomemnocumul_rake_19_logical-whole cuda:0 0

python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_1 logical-whole plotmachine_rake_1_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_2 logical-whole plotmachine_rake_2_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_3 logical-whole plotmachine_rake_5_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_3 logical-whole plotmachine_rake_10_logical-whole cuda:0 0
python test_longformer_filename_savedir_logdir_gpu_debug.py PlotmachineGenerations/plotmachine_rake/test/generations_outputs_3 logical-whole plotmachine_rake_19_logical-whole cuda:0 0

