#!/bin/sh
#SBATCH --job-name  zero_nextsentenceprediction-gpt
#SBATCH --time      96:00:00
#SBATCH -c          10
#SBATCH --mem       30G
#SBATCH --gpus      1
#SBATCH --mail-type END
#SBATCH --mail-user zzangmane@snu.ac.kr
source activate torch
#conda activate torch
ml cuda

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_booksumrake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_bk_booksumrake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_booksumrake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_bk_booksumrake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_booksumrake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_bk_booksumrake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_booksumrake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_bk_booksumrake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_booksumrake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_bk_booksumrake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_reedsyrake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_bk_reedsyrake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_reedsyrake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_bk_reedsyrake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_reedsyrake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_bk_reedsyrake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_reedsyrake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_bk_reedsyrake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_reedsyrake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_bk_reedsyrake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_wprake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_bk_wprake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_wprake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_bk_wprake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_wprake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_bk_wprake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_wprake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_bk_wprake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_bk_wprake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_bk_wprake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_booksumrake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_wp_booksumrake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_booksumrake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_wp_booksumrake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_booksumrake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_wp_booksumrake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_booksumrake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_wp_booksumrake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_booksumrake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_wp_booksumrake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_reedsyrake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_wp_reedsyrake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_reedsyrake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_wp_reedsyrake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_reedsyrake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_wp_reedsyrake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_reedsyrake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_wp_reedsyrake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_reedsyrake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_wp_reedsyrake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_wprake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_wp_wprake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_wprake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_wp_wprake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_wprake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_wp_wprake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_wprake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_wp_wprake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_wp_wprake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_wp_wprake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_booksumrake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_rd_booksumrake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_booksumrake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_rd_booksumrake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_booksumrake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_rd_booksumrake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_booksumrake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_rd_booksumrake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_booksumrake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_rd_booksumrake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_reedsyrake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_rd_reedsyrake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_reedsyrake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_rd_reedsyrake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_reedsyrake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_rd_reedsyrake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_reedsyrake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_rd_reedsyrake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_reedsyrake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_rd_reedsyrake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s

python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_wprake/test/generations_outputs_5 nextsentenceprediction-gpt zero_bart_rd_wprake_5_nextsentenceprediction-gpt cuda:0 5 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_wprake/test/generations_outputs_10 nextsentenceprediction-gpt zero_bart_rd_wprake_10_nextsentenceprediction-gpt cuda:0 10 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_wprake/test/generations_outputs_19 nextsentenceprediction-gpt zero_bart_rd_wprake_19_nextsentenceprediction-gpt cuda:0 19 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_wprake/test/generations_outputs_30 nextsentenceprediction-gpt zero_bart_rd_wprake_30_nextsentenceprediction-gpt cuda:0 30 0
sleep 1s
python test_longformer_filename_savedir_logdir_gpu_debug.py bartGenerations/zero_bart_rd_wprake/test/generations_outputs_50 nextsentenceprediction-gpt zero_bart_rd_wprake_50_nextsentenceprediction-gpt cuda:0 50 0
sleep 1s